name: Release Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get current version from git
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0)

      - name: Modify build.gradle with new version
        run: |
          sed -i "s/version = .*/version = '$(echo ${{ steps.get_version.outputs.VERSION }})'/" build.gradle

      - name: Build project
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GPR_USER: ${{github.actor}}
          GPR_TOKEN: ${{secrets.PUBLISH_PAT}}

